title: Jujutsu Kaisen
author: Redy Chee
email: cheesungyeng@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Jujutsu Kaisen is made by MAPPA. It has excellent fighting scenes. I recommend everyone to watch it. But be careful! Once your girl knows Gojou Satoru. It's GG!!!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  RedyChee # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
